// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registerDoctor.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	registerDoctor.proto

It has these top-level messages:
	Patient
	Doctor
	Schedule
	Slot
	ScheduleRecord
	ScheduleRequest
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Patient struct {
	UserId    string  `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	Email     string  `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	FirstName string  `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string  `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	Balance   float32 `protobuf:"fixed32,5,opt,name=Balance" json:"Balance,omitempty"`
}

func (m *Patient) Reset()                    { *m = Patient{} }
func (m *Patient) String() string            { return proto.CompactTextString(m) }
func (*Patient) ProtoMessage()               {}
func (*Patient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Patient) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Patient) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Patient) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Patient) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Patient) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type Doctor struct {
	UserId    string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	Level     string `protobuf:"bytes,5,opt,name=Level" json:"Level,omitempty"`
}

func (m *Doctor) Reset()                    { *m = Doctor{} }
func (m *Doctor) String() string            { return proto.CompactTextString(m) }
func (*Doctor) ProtoMessage()               {}
func (*Doctor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Doctor) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Doctor) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Doctor) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Doctor) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Doctor) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type Schedule struct {
	ScheduleId string                     `protobuf:"bytes,1,opt,name=ScheduleId" json:"ScheduleId,omitempty"`
	DoctorId   string                     `protobuf:"bytes,2,opt,name=DoctorId" json:"DoctorId,omitempty"`
	Records    map[string]*ScheduleRecord `protobuf:"bytes,3,rep,name=Records" json:"Records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Schedule) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *Schedule) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *Schedule) GetRecords() map[string]*ScheduleRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type Slot struct {
	TimeStart  uint64 `protobuf:"varint,1,opt,name=TimeStart" json:"TimeStart,omitempty"`
	TimeFinish uint64 `protobuf:"varint,2,opt,name=TimeFinish" json:"TimeFinish,omitempty"`
}

func (m *Slot) Reset()                    { *m = Slot{} }
func (m *Slot) String() string            { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()               {}
func (*Slot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Slot) GetTimeStart() uint64 {
	if m != nil {
		return m.TimeStart
	}
	return 0
}

func (m *Slot) GetTimeFinish() uint64 {
	if m != nil {
		return m.TimeFinish
	}
	return 0
}

type ScheduleRecord struct {
	RecordId    string `protobuf:"bytes,1,opt,name=RecordId" json:"RecordId,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	PatientId   string `protobuf:"bytes,3,opt,name=PatientId" json:"PatientId,omitempty"`
	Slot        *Slot  `protobuf:"bytes,4,opt,name=Slot" json:"Slot,omitempty"`
}

func (m *ScheduleRecord) Reset()                    { *m = ScheduleRecord{} }
func (m *ScheduleRecord) String() string            { return proto.CompactTextString(m) }
func (*ScheduleRecord) ProtoMessage()               {}
func (*ScheduleRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ScheduleRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *ScheduleRecord) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScheduleRecord) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *ScheduleRecord) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type ScheduleRequest struct {
	PatientId   string `protobuf:"bytes,1,opt,name=PatientId" json:"PatientId,omitempty"`
	DoctorId    string `protobuf:"bytes,2,opt,name=DoctorId" json:"DoctorId,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	Slot        *Slot  `protobuf:"bytes,4,opt,name=Slot" json:"Slot,omitempty"`
}

func (m *ScheduleRequest) Reset()                    { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()               {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ScheduleRequest) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *ScheduleRequest) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *ScheduleRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScheduleRequest) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func init() {
	proto.RegisterType((*Patient)(nil), "main.Patient")
	proto.RegisterType((*Doctor)(nil), "main.Doctor")
	proto.RegisterType((*Schedule)(nil), "main.Schedule")
	proto.RegisterType((*Slot)(nil), "main.Slot")
	proto.RegisterType((*ScheduleRecord)(nil), "main.ScheduleRecord")
	proto.RegisterType((*ScheduleRequest)(nil), "main.ScheduleRequest")
}

func init() { proto.RegisterFile("registerDoctor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x8b, 0x13, 0x31,
	0x18, 0xc6, 0x49, 0x67, 0xda, 0x6e, 0xdf, 0x8a, 0x4a, 0x28, 0x32, 0xae, 0xb2, 0x94, 0x39, 0x15,
	0x0f, 0x03, 0x56, 0x04, 0xf1, 0x58, 0xba, 0x0b, 0x85, 0x45, 0x4a, 0xaa, 0x17, 0x6f, 0xd9, 0x99,
	0x17, 0x37, 0xec, 0x34, 0x59, 0x93, 0xb4, 0xd0, 0x2f, 0xe0, 0x45, 0xfd, 0x6c, 0x7e, 0x25, 0xc9,
	0x9f, 0x99, 0x4e, 0x57, 0xd0, 0x9b, 0xb7, 0x3c, 0xcf, 0x3b, 0x79, 0xf2, 0xcb, 0x9b, 0x79, 0x61,
	0xa2, 0xf1, 0x8b, 0x30, 0x16, 0xf5, 0x52, 0x95, 0x56, 0xe9, 0xe2, 0x5e, 0x2b, 0xab, 0x68, 0xba,
	0xe5, 0x42, 0xe6, 0xdf, 0x09, 0x0c, 0xd7, 0xdc, 0x0a, 0x94, 0x96, 0x3e, 0x83, 0xc1, 0x27, 0x83,
	0x7a, 0x55, 0x65, 0x64, 0x4a, 0x66, 0x23, 0x16, 0x15, 0x9d, 0x40, 0xff, 0x72, 0xcb, 0x45, 0x9d,
	0xf5, 0xbc, 0x1d, 0x04, 0x7d, 0x09, 0xa3, 0x2b, 0xa1, 0x8d, 0xfd, 0xc0, 0xb7, 0x98, 0x25, 0xbe,
	0x72, 0x34, 0xe8, 0x39, 0x9c, 0x5d, 0xf3, 0x58, 0x4c, 0x7d, 0xb1, 0xd5, 0x34, 0x83, 0xe1, 0x82,
	0xd7, 0x5c, 0x96, 0x98, 0xf5, 0xa7, 0x64, 0xd6, 0x63, 0x8d, 0xcc, 0xbf, 0x11, 0x18, 0x04, 0xc8,
	0xff, 0x06, 0x33, 0x81, 0xfe, 0x35, 0xee, 0xb1, 0xf6, 0x28, 0x23, 0x16, 0x44, 0xfe, 0x8b, 0xc0,
	0xd9, 0xa6, 0xbc, 0xc5, 0x6a, 0x57, 0x23, 0xbd, 0x00, 0x68, 0xd6, 0x2d, 0x4e, 0xc7, 0x71, 0xf1,
	0x01, 0x7a, 0x55, 0x45, 0xaa, 0x56, 0xd3, 0xb7, 0x30, 0x64, 0x58, 0x2a, 0x5d, 0x99, 0x2c, 0x99,
	0x26, 0xb3, 0xf1, 0xfc, 0x45, 0xe1, 0xfa, 0x5e, 0x34, 0xdb, 0x8b, 0x58, 0xbd, 0x94, 0x56, 0x1f,
	0x58, 0xf3, 0xed, 0xf9, 0x1a, 0x1e, 0x75, 0x0b, 0xf4, 0x29, 0x24, 0x77, 0x78, 0x88, 0x67, 0xbb,
	0x25, 0x7d, 0x05, 0xfd, 0x3d, 0xaf, 0x77, 0xe8, 0x4f, 0x1c, 0xcf, 0x27, 0xa7, 0xb1, 0x61, 0x33,
	0x0b, 0x9f, 0xbc, 0xef, 0xbd, 0x23, 0xf9, 0x12, 0xd2, 0x4d, 0xad, 0xac, 0xeb, 0xd4, 0x47, 0xb1,
	0xc5, 0x8d, 0xe5, 0xda, 0xfa, 0xbc, 0x94, 0x1d, 0x0d, 0x77, 0x55, 0x27, 0xae, 0x84, 0x14, 0xe6,
	0xd6, 0x47, 0xa7, 0xac, 0xe3, 0xe4, 0x3f, 0x08, 0x3c, 0x3e, 0x3d, 0xc3, 0xdd, 0x3e, 0xac, 0xda,
	0xde, 0xb4, 0x9a, 0x4e, 0x61, 0xbc, 0x44, 0x53, 0x6a, 0x71, 0x6f, 0x85, 0x92, 0xb1, 0x39, 0x5d,
	0xcb, 0xe1, 0xc4, 0xdf, 0x6f, 0x55, 0x35, 0x0f, 0xd7, 0x1a, 0xf4, 0x22, 0x40, 0xfb, 0x47, 0x1b,
	0xcf, 0x21, 0xde, 0xb1, 0x56, 0x96, 0x79, 0x3f, 0xff, 0x49, 0xe0, 0xc9, 0x11, 0xe7, 0xeb, 0x0e,
	0x8d, 0x3d, 0x4d, 0x24, 0x0f, 0x13, 0xff, 0xf6, 0x56, 0x0f, 0x68, 0x93, 0x3f, 0x69, 0xff, 0xc1,
	0xb3, 0x78, 0x0d, 0xcf, 0x4b, 0xae, 0xb1, 0x30, 0xaa, 0xde, 0x63, 0x71, 0xc3, 0xcb, 0x3b, 0x94,
	0x55, 0x81, 0xd2, 0x0a, 0x7b, 0x58, 0xb4, 0x8d, 0x5b, 0xbb, 0xf9, 0x33, 0x9f, 0xfd, 0x00, 0xde,
	0x0c, 0xfc, 0x34, 0xbe, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x08, 0xcb, 0x58, 0x4b, 0xa5, 0x03,
	0x00, 0x00,
}
