// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registerDoctor.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	registerDoctor.proto

It has these top-level messages:
	PatientPublic
	DoctorPublic
	DoctorCollection
	Schedule
	Slot
	RegistrationInfo
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Slot_Type int32

const (
	Slot_FREE Slot_Type = 0
	Slot_BUSY Slot_Type = 1
)

var Slot_Type_name = map[int32]string{
	0: "FREE",
	1: "BUSY",
}
var Slot_Type_value = map[string]int32{
	"FREE": 0,
	"BUSY": 1,
}

func (x Slot_Type) String() string {
	return proto.EnumName(Slot_Type_name, int32(x))
}
func (Slot_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type PatientPublic struct {
	PatientId string `protobuf:"bytes,1,opt,name=PatientId" json:"PatientId,omitempty"`
}

func (m *PatientPublic) Reset()                    { *m = PatientPublic{} }
func (m *PatientPublic) String() string            { return proto.CompactTextString(m) }
func (*PatientPublic) ProtoMessage()               {}
func (*PatientPublic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PatientPublic) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

type DoctorPublic struct {
	DoctorId  string `protobuf:"bytes,1,opt,name=DoctorId" json:"DoctorId,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=LastName" json:"LastName,omitempty"`
}

func (m *DoctorPublic) Reset()                    { *m = DoctorPublic{} }
func (m *DoctorPublic) String() string            { return proto.CompactTextString(m) }
func (*DoctorPublic) ProtoMessage()               {}
func (*DoctorPublic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DoctorPublic) GetDoctorId() string {
	if m != nil {
		return m.DoctorId
	}
	return ""
}

func (m *DoctorPublic) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DoctorPublic) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type DoctorCollection struct {
	Doctors []*DoctorPublic `protobuf:"bytes,1,rep,name=doctors" json:"doctors,omitempty"`
}

func (m *DoctorCollection) Reset()                    { *m = DoctorCollection{} }
func (m *DoctorCollection) String() string            { return proto.CompactTextString(m) }
func (*DoctorCollection) ProtoMessage()               {}
func (*DoctorCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DoctorCollection) GetDoctors() []*DoctorPublic {
	if m != nil {
		return m.Doctors
	}
	return nil
}

type Schedule struct {
	ScheduleId string  `protobuf:"bytes,1,opt,name=ScheduleId" json:"ScheduleId,omitempty"`
	OwnerId    string  `protobuf:"bytes,2,opt,name=OwnerId" json:"OwnerId,omitempty"`
	Slots      []*Slot `protobuf:"bytes,3,rep,name=slots" json:"slots,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Schedule) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *Schedule) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Schedule) GetSlots() []*Slot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type Slot struct {
	SlotId           string            `protobuf:"bytes,1,opt,name=SlotId" json:"SlotId,omitempty"`
	TimeStart        uint64            `protobuf:"varint,2,opt,name=TimeStart" json:"TimeStart,omitempty"`
	TimeFinish       uint64            `protobuf:"varint,3,opt,name=TimeFinish" json:"TimeFinish,omitempty"`
	Avaliable        Slot_Type         `protobuf:"varint,4,opt,name=avaliable,enum=main.Slot_Type" json:"avaliable,omitempty"`
	RegistrationInfo *RegistrationInfo `protobuf:"bytes,5,opt,name=registrationInfo" json:"registrationInfo,omitempty"`
}

func (m *Slot) Reset()                    { *m = Slot{} }
func (m *Slot) String() string            { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()               {}
func (*Slot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Slot) GetSlotId() string {
	if m != nil {
		return m.SlotId
	}
	return ""
}

func (m *Slot) GetTimeStart() uint64 {
	if m != nil {
		return m.TimeStart
	}
	return 0
}

func (m *Slot) GetTimeFinish() uint64 {
	if m != nil {
		return m.TimeFinish
	}
	return 0
}

func (m *Slot) GetAvaliable() Slot_Type {
	if m != nil {
		return m.Avaliable
	}
	return Slot_FREE
}

func (m *Slot) GetRegistrationInfo() *RegistrationInfo {
	if m != nil {
		return m.RegistrationInfo
	}
	return nil
}

type RegistrationInfo struct {
	Description string `protobuf:"bytes,1,opt,name=Description" json:"Description,omitempty"`
	AttendeeId  string `protobuf:"bytes,2,opt,name=AttendeeId" json:"AttendeeId,omitempty"`
}

func (m *RegistrationInfo) Reset()                    { *m = RegistrationInfo{} }
func (m *RegistrationInfo) String() string            { return proto.CompactTextString(m) }
func (*RegistrationInfo) ProtoMessage()               {}
func (*RegistrationInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegistrationInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RegistrationInfo) GetAttendeeId() string {
	if m != nil {
		return m.AttendeeId
	}
	return ""
}

func init() {
	proto.RegisterType((*PatientPublic)(nil), "main.PatientPublic")
	proto.RegisterType((*DoctorPublic)(nil), "main.DoctorPublic")
	proto.RegisterType((*DoctorCollection)(nil), "main.DoctorCollection")
	proto.RegisterType((*Schedule)(nil), "main.Schedule")
	proto.RegisterType((*Slot)(nil), "main.Slot")
	proto.RegisterType((*RegistrationInfo)(nil), "main.RegistrationInfo")
	proto.RegisterEnum("main.Slot_Type", Slot_Type_name, Slot_Type_value)
}

func init() { proto.RegisterFile("registerDoctor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x25, 0x6c, 0xda, 0xee, 0xce, 0x42, 0x89, 0x2c, 0x54, 0x85, 0x0a, 0xa1, 0x28, 0xa7, 0x1c,
	0x68, 0x24, 0x96, 0x3f, 0x00, 0xa1, 0x5d, 0xa9, 0x12, 0x82, 0x95, 0xb3, 0x1c, 0xe0, 0xe6, 0x24,
	0x53, 0x6a, 0xe1, 0xb5, 0x57, 0xb6, 0x5b, 0xb4, 0xbf, 0x99, 0x3f, 0x81, 0x1c, 0xe7, 0x4b, 0xdb,
	0x53, 0xf2, 0xde, 0xcc, 0xbc, 0x79, 0x33, 0x1e, 0x78, 0xad, 0xf1, 0x37, 0x37, 0x16, 0xf5, 0xb5,
	0xaa, 0xad, 0xd2, 0xf9, 0x5e, 0x2b, 0xab, 0x48, 0xb8, 0x63, 0x5c, 0xa6, 0x57, 0xf0, 0x72, 0xc3,
	0x2c, 0x47, 0x69, 0x37, 0x0f, 0x95, 0xe0, 0x35, 0x79, 0x0b, 0x8b, 0x8e, 0xb8, 0x6d, 0xe2, 0x20,
	0x09, 0xb2, 0x05, 0x1d, 0x89, 0xb4, 0x81, 0x17, 0x5e, 0xa4, 0xcb, 0xbe, 0x84, 0xb9, 0xc7, 0x43,
	0xf2, 0x80, 0x9d, 0xd2, 0x9a, 0x6b, 0x63, 0xbf, 0xb1, 0x1d, 0xc6, 0xcf, 0xbd, 0xd2, 0x40, 0xb8,
	0xca, 0xaf, 0xac, 0x0b, 0xce, 0x7c, 0x65, 0x8f, 0xd3, 0x4f, 0x10, 0x79, 0x95, 0x2f, 0x4a, 0x08,
	0xac, 0x2d, 0x57, 0x92, 0xbc, 0x87, 0xb3, 0xa6, 0xe5, 0x4c, 0x1c, 0x24, 0xb3, 0x6c, 0xb9, 0x22,
	0xb9, 0x1b, 0x20, 0x9f, 0xda, 0xa1, 0x7d, 0x4a, 0x7a, 0x07, 0xf3, 0xb2, 0xbe, 0xc7, 0xe6, 0x41,
	0x20, 0x79, 0x07, 0xd0, 0xff, 0x0f, 0x2e, 0x27, 0x0c, 0x89, 0xe1, 0xec, 0xfb, 0x5f, 0x89, 0x6e,
	0x04, 0xef, 0xb2, 0x87, 0x24, 0x81, 0x13, 0x23, 0x94, 0x35, 0xf1, 0xac, 0xed, 0x08, 0xbe, 0x63,
	0x29, 0x94, 0xa5, 0x3e, 0x90, 0xfe, 0x0b, 0x20, 0x74, 0x98, 0x5c, 0xc0, 0xa9, 0xfb, 0x0e, 0x0d,
	0x3a, 0xe4, 0x96, 0xb0, 0xe5, 0x3b, 0x2c, 0x2d, 0xd3, 0xb6, 0x95, 0x0f, 0xe9, 0x48, 0x38, 0x6b,
	0x0e, 0xac, 0xb9, 0xe4, 0xe6, 0xbe, 0x5d, 0x43, 0x48, 0x27, 0x0c, 0xb9, 0x82, 0x05, 0x7b, 0x64,
	0x82, 0xb3, 0x4a, 0x60, 0x1c, 0x26, 0x41, 0x76, 0xbe, 0x7a, 0x35, 0x9a, 0xc8, 0xb7, 0x87, 0x3d,
	0xd2, 0x31, 0x83, 0x14, 0x10, 0xf9, 0xa7, 0xd6, 0xcc, 0xed, 0xec, 0x56, 0xde, 0xa9, 0xf8, 0x24,
	0x09, 0xb2, 0xe5, 0xea, 0xc2, 0x57, 0xd1, 0xa3, 0x28, 0x7d, 0x92, 0x9f, 0x5e, 0x42, 0xe8, 0x64,
	0xc9, 0x1c, 0xc2, 0x35, 0xbd, 0xb9, 0x89, 0x9e, 0xb9, 0xbf, 0xe2, 0x47, 0xf9, 0x33, 0x0a, 0xd2,
	0x2d, 0x44, 0xc7, 0x0a, 0x24, 0x81, 0xe5, 0x35, 0x9a, 0x5a, 0xf3, 0xbd, 0xa3, 0xba, 0xe9, 0xa7,
	0x94, 0x1b, 0xf2, 0xb3, 0xb5, 0x28, 0x1b, 0xc4, 0x61, 0xc5, 0x13, 0xa6, 0xf8, 0x00, 0x6f, 0x6a,
	0xa6, 0x31, 0x37, 0x4a, 0x3c, 0x62, 0x5e, 0xb1, 0xfa, 0x0f, 0xca, 0x26, 0x47, 0x69, 0xb9, 0x3d,
	0x14, 0xe7, 0xfd, 0x43, 0x6d, 0xdc, 0xd1, 0x9a, 0x5f, 0xed, 0xd5, 0x56, 0xa7, 0xed, 0x09, 0x7f,
	0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x13, 0xfe, 0x81, 0x0c, 0xda, 0x02, 0x00, 0x00,
}
